
spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.89.121:26379,192.168.89.121:26380,192.168.89.121:26381
server:
  port: 80