server:
  port: 8888
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
security:
  ignore:
    urls:
      - /druid/**
      - /redis/**
spring:
  redis:
    host: 192.168.3.33
    port: 6379